### ISSUE TITLE
مسیر هلند به ایران

### ISSUE THREAD

**Issue by saeedm1997** [dev-ir/assistant-vps#1]
سلام وقت بخیر
من 4 روز پیش کل تانلام از کار افتاد، خارجم هلند بود

بعد کلی تست متوجه شدم ارتباط هلند به دیتاسنترم قطع شده، پینگ اکی بود، ولی ssh نمیشد زد

اول فکر کردم محدود شدم، هلند از جاهای مختلف خریداری کردم ولی بازم متصل نشد

از هلند به ip ایران تمیز که اصلا تانل استفاده نشده بود تست کردم بازم نشد ( به رنج 185 متصل نمیشد ولی 94 میشد)

از هلند به دیتاسنتر مبین هاست تست کردم بازم ارتباط برقرار نشد اونم رنج 185 بود

ولی از هلند به دیتاسنتر امین و اروان اکی بود همه چیز

و از لوکیشنای دیگه مثل المان هم به دیتاسنتر اولم اکی بود

مشکل هنوزم ادامه داره

به نظرتون اختلال بین مسیر های اینترنته؟

**Comment by dev-ir** [comment]
سلام این موارد مربوط به تانل هست
