### ISSUE TITLE
ایپی اسکن و تورنت

### ISSUE THREAD

**Issue by Mohammadaminsdr** [dev-ir/assistant-vps#3]
سلام وقت بخیر 

خسته نباشید بابت نوشتن این اسکریپت خفن دوتا پیشنهاد داشتم

یکیش ایپی اسکن و دومی تورنت هستش که بشه بلاک کرد داخل سرور و شما به اسکریپت اضافه اش کنید عالی میشه :)

**Comment by Mohammadaminsdr** [comment]
؟؟؟

**Comment by dev-ir** [comment]
به خاطر موارد مثل تانل نمیشه دقیق این کار انجام داد و به اسکریپت اضافه کرد 
چون کلاینت های مختلف وجود دارد که رمزنگاری های پیچیده تری استفاده میکنند
و یا تانل ها با رمزنگاری های خاص باعث میشن که ترافیک های تورنت قابل تشخیص نباشند
